project_id = "rlhlzizvneeacdmsqrxx"

[functions.bot-monitor]
verify_jwt = false

[functions.execute-swap]
verify_jwt = false

[functions.news-scanner]
verify_jwt = false

[functions.position-monitor]
verify_jwt = false

[functions.wallet-discovery]
verify_jwt = false

[functions.token-sentiment]
verify_jwt = false

[functions.get-helius-key]
verify_jwt = false

[functions.find-active-wallets]
verify_jwt = false

[functions.bot-health]
verify_jwt = false

[functions.bot-api]
verify_jwt = false
